/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bookingFrame;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import userFrame.ListBooking;

/**
 *
 * @author ASUS
 */
public class inputTanggal extends javax.swing.JFrame {
    private static int userId;
    
    private JToggleButton togel1;
    private JToggleButton togel2;
    private JToggleButton togel3;
    private JToggleButton togel4;
    private JToggleButton togel5;
    private JToggleButton togel6;
    private JToggleButton togel7;
    private JToggleButton togel8;
    private JToggleButton togel9;
    private JToggleButton togel10;
    private JToggleButton togel11;
    private JToggleButton togel12;
    private JToggleButton togel13;
    private JToggleButton togel14;

    /**
     * Creates new form inputTanggal
     */
    public inputTanggal(int userId) {
        initComponents();
        this.userId = userId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jButtonHome = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButtonBack = new javax.swing.JButton();
        dateChooser = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxLapangan = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButtonBooking = new javax.swing.JButton();

        jPanel6.setBackground(new java.awt.Color(37, 75, 98));

        jButtonHome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonHome.setForeground(new java.awt.Color(29, 62, 83));
        jButtonHome.setText("Home");
        jButtonHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonHome)
                .addContainerGap(726, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jButtonHome)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(71, 109, 124));
        jPanel1.setMinimumSize(new java.awt.Dimension(300, 220));
        jPanel1.setPreferredSize(new java.awt.Dimension(120, 200));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(37, 75, 98));

        jButtonBack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonBack.setForeground(new java.awt.Color(29, 62, 83));
        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonBack)
                .addContainerGap(726, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jButtonBack)
                .addContainerGap())
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));
        jPanel1.add(dateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 170, -1));

        jLabel1.setText("Lapangan             :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jComboBoxLapangan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lapangan 1 (rumput) 150k/jam", "Lapangan 2 (karpet) 175k/jam", " ", " " }));
        jComboBoxLapangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLapanganActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxLapangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 170, -1));

        jLabel2.setText("Tanggal Booking :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jButtonBooking.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButtonBooking.setForeground(new java.awt.Color(29, 62, 83));
        jButtonBooking.setText("Booking");
        jButtonBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBookingActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBooking, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomeActionPerformed
        this.hide();
        ListBooking userFrame = new ListBooking(userId);
        userFrame.show();

    }//GEN-LAST:event_jButtonHomeActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        this.hide();
        ListBooking userFrame = new ListBooking(userId);
        userFrame.show();

    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBookingActionPerformed

         
            java.util.Date utilDate = dateChooser.getDate();
            
            if (utilDate == null) {
                JOptionPane.showMessageDialog(this, "Isiki dulu tanggalnya.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
                return;
            }
            long utilTime = utilDate.getTime();
            java.sql.Date sqlDate = new java.sql.Date(utilTime);

            int lapangan = jComboBoxLapangan.getSelectedIndex()+1;
            if((lapangan == 0) || (lapangan > 2)|| jComboBoxLapangan.getSelectedItem().toString().equals("Pilih Lapangan")){
               JOptionPane.showMessageDialog(this, "Pilih lapangan terlebih dahulu.", "Kesalahan", JOptionPane.ERROR_MESSAGE);
               return; 
            }
            
            BookingBean newBookingBean = new BookingBean(lapangan, sqlDate);
            bookingFrameBal bfbObj = new bookingFrameBal();

            List<Object> toggleButtons = Arrays.asList(togel1, togel2, togel3, togel4, togel5, togel6, togel7, togel8, togel9, togel10, togel11, togel12, togel13, togel14);

            List<BookingBean> bookings = bfbObj.isAvailable(sqlDate, lapangan);

            this.setVisible(false);

            BookingRequest bookingRequestFrame = new BookingRequest(bookings,sqlDate,lapangan,userId);
            bookingRequestFrame.setVisible(true);


    }//GEN-LAST:event_jButtonBookingActionPerformed

    private void jComboBoxLapanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLapanganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxLapanganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inputTanggal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inputTanggal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inputTanggal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inputTanggal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inputTanggal(userId).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonBooking;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JComboBox<String> jComboBoxLapangan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
